image: archlinux
packages:
  - racket
  - python
  - python-pygments
  - p7zip
  - cask
  - emacs-nox
sources:
  - https://github.com/kisaragi-hiu/kisaragi-hiu.com
secrets:
  - 9971994c-ebe1-4f42-bb58-11e57b65c689
tasks:
  - install-racket-packages: |
      raco pkg install --skip-installed --deps search-auto pollen txexpr threading
  - build: |
      cd kisaragi-hiu.com
      make zip
  - deploy: |
      cd kisaragi-hiu.com
      bash deploy.sh > /dev/null
