image: archlinux
packages:
  - racket
  - python
  - python-pygments
  - p7zip
sources:
  - https://github.com/kisaragi-hiu/kisaragi-hiu.com
secrets:
  - 5c8f8983-4435-4e42-8388-2fa7987794aa
tasks:
  - install-racket-packages: |
      raco pkg install --skip-installed --deps search-auto pollen txexpr threading css-expr
  - build: |
      cd kisaragi-hiu.com
      make zip
  - deploy: |
      cd kisaragi-hiu.com
      bash deploy.sh > /dev/null
