image: archlinux
packages:
  - p7zip
  - hugo
  - nodejs
  - npm
sources:
  - https://github.com/kisaragi-hiu/kisaragi-hiu.com
secrets:
  - 9971994c-ebe1-4f42-bb58-11e57b65c689
  - d00ee754-d764-4ca4-8ff5-498ed5d4ae7b
tasks:
  - npm: |
      cd kisaragi-hiu.com
      npm install --production
  - build: |
      cd kisaragi-hiu.com
      make zip
  - deploy: |
      cd kisaragi-hiu.com
      bash deploy.sh > /dev/null
