image: archlinux
packages:
  - p7zip
  - hugo
  - ruby-sass
sources:
  - https://github.com/kisaragi-hiu/kisaragi-hiu.com
secrets:
  - 9971994c-ebe1-4f42-bb58-11e57b65c689
tasks:
  - build: |
      cd kisaragi-hiu.com
      make zip
  - deploy: |
      cd kisaragi-hiu.com
      bash deploy.sh > /dev/null
