language: python
python: 3.6
sudo: false
branches:
  only:
  - source
env:
  global:
  - RACKET_DIR: "~/racket"
  - RACKET_VERSION: 6.11
  - GH_REF: 'github.com/flyingfeather1501/flyingfeather1501.github.io.git'
before_install:
- pushd ~/
- git clone https://github.com/greghendershott/travis-racket.git ~/travis-racket
- cat ~/travis-racket/install-racket.sh | bash
- export PATH="${RACKET_DIR}/bin:${PATH}"
- popd
install:
- raco pkg install --deps search-auto pollen frog pollen-component txexpr threading css-expr
- pip install pygments
script:
- bash ./build.sh publish
deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: source
