language: python
python: 3.6
sudo: false
branches:
  only:
  - source
env:
  global:
  - RACKET_DIR: "~/racket"
  - RACKET_VERSION: 6.10.1
  - GH_REF: 'github.com/flyingfeather1501/flyingfeather1501.github.io.git'
  - secure: "zhx1LxLtoIjA2UQwpeoF9BWm08X2op2Ko39927tiwgQpLJSeOS33bsx/BKUU8iNEXXjYxeAqUIgrINdLSmW0/cbsgjDKdNhx6q0VZ6kvIja5TPe3NO2rGHsBZJAw2Zg7U6pUJYeEi113KM76ntAGrJI+aCqShvupAURCWn7+S6rdL2VWQpkM2c+bIWp/3tFyiFUr//NBtZ9+rbPlLuUKiQ+XPY38c9CU8zqZnw1MUwthyNz99O5zr1aqL2py1G2cxnCAHJEK1Dm8gdXBNs8Z1G/zaS/+MmA8gAje0blCLnKB2dppTeHMxlh75g8Oq8j8hYdjwbXsBh88bJuC66ua2Dtgpn3uRzwwO6DQ/lrZJgNOosJbFgHiGueFdgBGfXiBUQsgjPAWtyDpeCpBcSuIB4TMQ9Vw5O/w0boSLybk1UmicmRaGOVjQK+h5zJJNsOROp2/02o3/tkhrNLlvR/kV0Bkh8uJFMddHqtmtrwip+MSBJ0jQ7f/p9ZHwhuWzH8QSseaaCaGCOIOU3Y7AnVN2g+3+L16ZGUR/IoT7AHvC9RvyAqLDllN2U3SFCLtN7IQRj1jYWDA/rrFWe4h0p3ah2qn/wuZHzrW7OSYQssV1UHjvotnXPoiKA/uKP7BEM5gILVXIQNX3gi2J0a9zjB2fpFJ2nFShl9ts0g/R7RIQKM="
  - secure: "fb1+hqbXzxgmRu3yeqhflRYQgPCuv7LPWkTmeYlivAK2Y6Pd78sg0/JLMXwDhEsUvsmXDJrCvpYSYhuiqHNOgYjwWyA5fJlciXf4r9Pmgd5VtRObQqGzigthi6Tej4PMqPouNYb6X4kFJ0EWc9w7KBCjCI3mbnGdNADmAIyjR058SSG8XxXEg3xl58hDYEYx0iCRmKMPAMuNVYVtCMoGMNal4azuIMGoNBLatruSjgGcKlUG9sIENF6kNlRDR9vxq1QR6F4I7oLvtIeKD2p2P+8lsTr5vI5CwQ2bxpL0dPyCiodP/2LLWpMkDFP1/J1DC17SJ49fo+ofErseffGqnCf1Rjkxp8HLw/8UVLjMtbuPeQWPAyrQN5lZmg5BbC+Coi156yoHpXlADo3LHWTXzZb6s4xtUFig7Cx/8afjtV17Q21QE268uRBjzjZL6pYrDqpQWE7hoD+1huCEGyeF+J7fHzXq+GMKgryXd6iudg9lAkMVounwTJxxPJaeAzDpCu0H/4GubC+Znyq5h+QMv5TgzCMi4XQ13JtWbGX1PEdKRD+RoZ9EN48rnFp695Cij6w+o1//cAPWut7iImERxVMldW498VClDoQmxsjxo8Mx8vmFsieNgHrkG3rizBL1stHUOUcZ7XdruUPXvtU7TTclMJ/G24vyiCWRxmz6W2Y="
before_install:
- pushd ~/
- git clone https://github.com/greghendershott/travis-racket.git ~/travis-racket
- cat ~/travis-racket/install-racket.sh | bash
- export PATH="${RACKET_DIR}/bin:${PATH}"
- popd
install:
- raco pkg install --catalog https://pkg-build.racket-lang.org/server/built/catalog/ --deps search-auto pollen hyphenate pollen-count pollen-component txexpr threading shell-pipeline rackjure css-expr
- pip install pygments
script:
- bash ./build.sh publish
deploy:
  provider: script
  script: bash ./deploy.sh
  skip_cleanup: true
  on:
    branch: source
