language: python
python: 3.6
branches:
  only:
  - source
env:
  global:
  - RACKET_DIR: "~/racket"
  - RACKET_VERSION: 7.4
  - GH_REF: 'github.com/kisaragi-hiu/kisaragi-hiu.com.git'
cache:
  directories:
    - $HOME/.racket/$RACKET_VERSION/
before_install:
- pushd ~/
- git clone https://github.com/greghendershott/travis-racket.git ~/travis-racket
- cat ~/travis-racket/install-racket.sh | bash
- export PATH="${RACKET_DIR}/bin:${PATH}"
- popd
install:
- raco pkg install --skip-installed --deps search-auto pollen txexpr threading css-expr
- pip install pygments
script:
- bash ./build.sh publish
deploy:
  edge: true
  provider: netlify
  site: a9979c17-2cfe-4bc9-9dd9-ee9e6bf1b161
  dir: "public"
  prod: true
  on:
    branch: source
