language: python
python: 3.6
sudo: false

branches:
    only:
        - source

env:
    global:
        - RACKET_DIR: '~/racket'
        - RACKET_VERSION: '6.10.1'

before_install:
    - git clone https://github.com/greghendershott/travis-racket.git ~/travis-racket
    - cat ~/travis-racket/install-racket.sh | bash
    - export PATH="${RACKET_DIR}/bin:${PATH}"

install:
    - raco pkg install --deps search-auto pollen hyphenate pollen-count txexpr threading shell-pipeline rackjure
    - pip install pygments

script:
    - bash ./build.sh publish

deploy:
    provider: pages
    skip_cleanup: true
    github_token: $GH_TOKEN
    local_dir: $HOME/public
    target_branch: master
    on:
        branch: source
